[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --workspace=packages/web"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build:web"]

[start]
cmd = "npm run start --workspace=packages/web"
