[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npx vite preview --port $PORT --host 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "3000"
NODE_ENV = "production"
VITE_API_URL = "${{ VITE_API_URL }}"
VITE_CALENDAR_SERVICE_URL = "${{ VITE_CALENDAR_SERVICE_URL }}"
VITE_DIARY_SERVICE_URL = "${{ VITE_DIARY_SERVICE_URL }}"
VITE_SAJU_SERVICE_URL = "${{ VITE_SAJU_SERVICE_URL }}"