[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "8082"
NODE_ENV = "production"
DATABASE_URL = "${{ DATABASE_URL }}"
CORS_ORIGIN = "${{ CORS_ORIGIN }}"